### ISSUE TITLE
init produces an error that `config/config.yaml` is missing

### ISSUE THREAD

**Issue by ep1cman** [DataDog/apigentools#184]
**Overview of issue:**
Running the init command produces an error.

**Steps to reproduce the issue:**
1. Install latest version
2. run the command: `apigentools init myspecrepo`

**Describe the results you received:**
`ERROR: Couldn't find config/config.yaml. Are you running in spec repo?"

**Describe the results you expected:**
The command should generate a folder structure including the config.yaml file.

**Additional information you deem important (e.g. issue happens only occasionally):**
The cause is the following line: https://github.com/DataDog/apigentools/blob/fc153b84ad35e95d44f6fc151940eba9c8375ac4/apigentools/cli.py#L92
This produces an error if the YAML file is missing, but this should not be checked when invoking the `init` subcommand

**Comment by bkabrda** [comment]
Hey 👋 thanks for the report. I fixed this issue in #186 and released in apigentools 1.1.0: https://apigentools.readthedocs.io/en/latest/changelog/#110-2020-05-13
